### ISSUE TITLE
What Editor and plugins do you use?

### ISSUE THREAD

**Issue by jorgeitenjr** [coryhouse/ama#10]
Hi there,
Do you mind to share the editor you're currently using? VS Code? Which plugins do you use? Do you use any specific theme, font colors, prettier, etc?

**Comment by coryhouse** [comment]
I use VSCode. [Here's my current list of plugins](https://www.dropbox.com/s/qfoemwqsk5i18ae/Screenshot%202018-05-29%2011.42.25.png?dl=0).

I typically use a light theme since I tend to work in bright environments during the day.

**Comment by jorgeitenjr** [comment]
I can't open the link 😦

**Comment by coryhouse** [comment]
Oops, file is uploading and will be there soon.
