### ISSUE TITLE
My Information Stream

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/ama#11]
I believe it's critical to manicure your information stream to assure it's providing a high signal-to-noise ratio. 

A valuable information stream:
- **Is high signal**: Consistently provides information that helps you achieve your goals
- **Is low noise**: Avoids providing information that's outside your realm of influence

>“In ancient times, having power meant having access to data. Today, having power means knowing what to ignore. - Yuval Harari

# My Goals

- I am currently focused on JavaScript, React, Node, and GraphQL. So my information stream reflects this focus. 
- I've found improving my general life skills has dramatically improved my quality of life and my results. So I regularly consume useful content that's unrelated to programming, but broadens my knowledge. Topics include psychology, health, communication, persuasion, sales, management, lifestyle design, time management, mental models, and so on. I take my lessons in these areas and regularly consider how they apply to programming.

# Social Media

[I follow many developers on Twitter](http://www.twitter.com/housecor). I limit the time I spend reading tweets so I can focus my reading on the sources below. I don't use any other social media.

# Email Newsletters

I'm a big believer in this format. The signal to noise ratio on these is high.

### General

[Farnham Street Brain Food Newsletter](https://www.fs.blog/newsletter/)
[Seth Godin’s daily blog](https://www.sethgodin.com)
[Tim Ferriss Mailing List](http://go.fourhourworkweek.com/10x-output/)

### JavaScript
[JavaScript Weekly](https://javascriptweekly.com/issues/384)
[Es.next News](https://mailchi.mp/c4967f7b8ab6/1ibwllby24?e=8204930852)
[React.js Newsletter](http://reactjsnewsletter.com/issues/116)
[React Status](https://react.statuscode.com)
[O'Reilly Web Development Newsletter](https://get.oreilly.com/email-signup.html)
[React Digest](https://reactdigest.net)
[Kent C Dodds Mail](https://kcd.im/news)
 
# Podcasts

### General

[The Knowledge Project ](https://www.fs.blog/the-knowledge-project/)
[Tim Ferriss Show](https://tim.blog/podcast/)

### JavaScript
[The React Podcast](http://reactpodcast.com/)
[JavaScript Jabber](https://devchat.tv/js-jabber)
[Syntax](https://syntax.fm)

# Books

I use [audible](http://www.audible.com). I listen to about one book a month while driving and biking. I track my reads on [GoodReads](https://www.goodreads.com/review/list/40867232).

# Video

I watch [Pluralsight](http://www.pluralsight.com) and [Egghead](http://www.egghead.io) courses. I believe in video-based learning, so I've [authored multiple courses on Pluralsight](https://app.pluralsight.com/profile/author/cory-house).

I also enjoy [Fun Fun Function](https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q) on YouTube and [TED Talks](http://www.ted.com).

I hardly ever watch TV. I prefer reading, writing, experimenting, traveling, and hanging out with the fam. 

# Conferences

I enjoy speaking at conferences so I can get in and learn for free. 👍 Although I enjoy the "hallway track", I often attend sessions. [Here's the list of conferences I've attended](https://www.bitnative.com/presentations/).

# News

I don't watch/read general news. [Here's why](https://www.fs.blog/2013/12/stop-reading-news/). [The Four Hour Work Week](https://www.amazon.com/4-Hour-Workweek-Escape-Live-Anywhere/dp/0307465357/ref=sr_1_1?ie=UTF8&qid=1529263637&sr=8-1&keywords=the+four+hour+work+week) also has good insights on this topic. If it's a big deal, it tends to come to my attention anyway via Twitter and word of mouth.  I rarely visit general tech sites since my email stream has a higher signal to noise ratio for my interests, and conference sessions and conversations fill in the gaps.

# Sports

I often watch my kids play sports. 😃 Not much else.

# Music

I don't listen to the radio because the ads are obnoxious and I prefer to [multithread my commuting](http://outlierdeveloper.com/audiobooks/). I strive to avoid ads. Instead, I listen to audio books and podcasts, and I pay for Spotify so there are no ads. I have a "[Deep Focus](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWZeKCadgRdKQ?si=HG62E0T7TIy2tFG6FvWuvQ)" playlist for coding that contains music without lyrics.

**Comment by kolawoletech** [comment]
Loving this.

**Comment by mihailgaberov** [comment]
Very useful, filling the gaps in my list. Thanks for sharing!

**Comment by phanib** [comment]
Awesome list. Learned some new things.

**Comment by jasonkarns** [comment]
This is awesome! Luckily most of those email newsletters still publish RSS feeds so I can consume via feedly instead of polluting my inbox.

**Comment by hicks86** [comment]
This is a great! Btw is the Spotify "Deep focus" playlist public?

**Comment by coryhouse** [comment]
@hicks86 - Thanks! Yep, it's [here](https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWZeKCadgRdKQ?si=HG62E0T7TIy2tFG6FvWuvQ). I just updated the post to include this link.
