### ISSUE TITLE
What is the best way to be comfortable with JS?

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/ama#18]
Hello mister Cory House  I'm Firas Regayeg from Tunisia, I'm a new junior developer. I work now for an enterprise that would use new technologies in its product developments. I followed you on Pluralsight and got many things new in JS thank you so much for those useful tutos. But for now, I want to contact you about something else, that I'm NOT ok with it. Its about when I start something new by myself trying to make it without help of others , I stuck up immediately. Could you tell me please, what is the best way to be comfortable with JS - specially - I want to be good on it, its the future language.  I will be thankful for any instructions or recommendations from you. Thanks in advance

**Comment by coryhouse** [comment]
I would begin by getting comfortable with the language itself. Learn the syntax and keywords. Learn the modern features that have been added in ES2016, 2017, 2018. Use the browser dev tools.  Read [MDN](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics). Along the way, build something real to put your learning to use. Start small and slowly expand the app. This concrete action will help you truly understand what you read. 

Hope that helps!

**Comment by mikybars** [comment]
Do you recommend Javascript: The Good Parts? I'm considering giving it a try

**Comment by coryhouse** [comment]
I read it many years ago and found it useful at the time, but it's quite dated at this point.
