### ISSUE TITLE
How much money have you generated from PluralSight courses over their lifetime?

### ISSUE THREAD

**Issue by barnomics** [coryhouse/ama#19]
And, do you get paid a flat fee at PluralSight, or per view like a Spotify, or something else?

**Comment by coryhouse** [comment]
I'm not comfortable sharing specifics about my income, but I can say this about Pluralsight's model: They pay a flat fee up front, and then a percentage of "royalties" for the amount of time viewed. A few authors make a lot of money, many make a little. You can think of it a lot like being a musician. A few lucky people who are very popular make a lot. Others who don't get many views, make a little.
