### ISSUE TITLE
What is you opinion on createSharedState React RFC

### ISSUE THREAD

**Issue by mucsi96** [coryhouse/ama#21]
Hi Cory,

I am your follower and very impressed with your React knowledge. I would like to ask your feedback on my first (React RFC)[https://github.com/reactjs/rfcs/pull/130]. I think it could be very valuable for the whole React community. How do you see it from your perspective?

**Comment by coryhouse** [comment]
Hi - Sorry, I just saw this. Since this was asked long ago, closing.
