### ISSUE TITLE
Building Applications in React and Redux

### ISSUE THREAD

**Issue by KaricAnes** [coryhouse/ama#23]
Hey Cory, i want to run your application from pluralsight course 

1) I downloaded exercise files from PluralSight: module 10, after folder. Asinq in Redux

2) Then i navigated to this folder:
C:\Users\asus\Desktop\CoryMaterMuJBM\after   

3) and eneterd npm install to get node modulles. 

4) Then i run: 
C:\Users\asus\Desktop\CoryMaterMuJBM\after>npm start

5) and get his message:
 

 ps-redux@ start C:\Users\asus\Desktop\CoryMaterMuJBM\after
> run-p start:dev start:api

> ps-redux@ start:dev C:\Users\asus\Desktop\CoryMaterMuJBM\after
> webpack-dev-server --config webpack.config.dev.js --port 3000

> ps-redux@ prestart:api C:\Users\asus\Desktop\CoryMaterMuJBM\after
> node tools/createMockDb.js

Mock DB created.

> ps-redux@ start:api C:\Users\asus\Desktop\CoryMaterMuJBM\after
> node tools/apiServer.js

events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3001
    at Server.setupListenHandle [as _listen2] (net.js:1298:14)
    at listenInCluster (net.js:1346:12)
    at Server.listen (net.js:1434:7)
    at Function.listen (C:\Users\asus\Desktop\CoryMaterMuJBM\after\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\asus\Desktop\CoryMaterMuJBM\after\tools\apiServer.js:59:8)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1325:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3001
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ps-redux@ start:api: `node tools/apiServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ps-redux@ start:api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2020-05-23T20_25_42_332Z-debug.log
ERROR: "start:api" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ps-redux@ start: `run-p start:dev start:api`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ps-redux@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2020-05-23T20_25_42_751Z-debug.log

**Comment by coryhouse** [comment]
That means port 3001 is already in use on your machine. Perhaps you already have this running in a separate terminal? Also, please post on the course discussion for support. Happy coding!

**Comment by KaricAnes** [comment]
I killed all running processes on 3001 port with this commands:

netstat -ano | findstr :3001
tskill typeyourPIDhere


Now it works perfectly. Tnx Cory for qick answer.
