### ISSUE TITLE
How to go fully independent in the software business?

### ISSUE THREAD

**Issue by spacentime** [coryhouse/ama#25]
I've been a software engineer for many years now and the last few years I’ve been doing it on a contract basis. Typically contracting with one company at a time through staffing agencies. Contracting has its benefits but in most ways it is like an employee, I exchange my service on a per hour basis which obviously has its limitations.
I would like to expand my business in a way that I can serve multiple clients and offer my services on a per service basis and not just by the hour.
Do you have any advice on how to do that?

**Comment by coryhouse** [comment]
Here's a good resource on ditching hourly: https://podcast.ditchinghourly.com/
