### ISSUE TITLE
React in Visual Studio

### ISSUE THREAD

**Issue by JSerwatien** [coryhouse/ama#26]
Hi Cory.  I was wondering if you gave any courses in React using Visual Studio.  I am a Microsoft developer and even though I have a subscription to Pluralsight, I don't see any courses like this. Thanks

**Comment by coryhouse** [comment]
Sorry, I don't, and I'm not aware of many people using Visual Studio with React. Most teams I work with prefer to use VSCode for the front-end, and Visual Studio for the backend.

**Comment by JSerwatien** [comment]
I just finished your React with Flux course on Pluralsight.  Excellent!  Thank you

Joshua Serwatien
The Great Idea Factory
(561) 244-5696
(717) 427-1321 (fax)
http://www.greatideafactory.com<http://www.greatideafactory.com/>
josh@greatideafactory.com<mailto:josh@greatideafactory.com>

________________________________

**Comment by coryhouse** [comment]
Wonderful to hear! Thanks for the kind feedback! :)
