### ISSUE TITLE
Chasing Fears

### ISSUE THREAD

**Issue by accidentaldeveloper** [coryhouse/ama#27]
In your talk, ["The Immutable Laws of Software and Life"](https://www.pluralsight.com/courses/codemash-session-30) you discuss the importance of "chasing your fears". You mention the fear of public speaking as one of the fears that you chased and overcame. This fear is clearly not an obstacle any more. 😀

Having conquered this fear, what fears are you chasing now?

**Comment by coryhouse** [comment]
Hi Michael - I love this question. In fact, this is the most helpful question anyone has asked me so far. 

For 20 years I wanted to be an independent consultant and author. But I was scared of independence. I finally conquered that fear last September. And I'm loving life. For the last year, I've felt like I conquered my last great fear. I've never been happier, or felt more free.

But after considering your question, I realize I have more fears to conquer. And I realize now why going independent scared me for 20 years. My greatest fear is being poor. 

I grew up feeling poor. I had a stable home with loving parents, but money was tight. I was picked on at school for having cheap clothes. We rarely went out to eat. We only vacationed 3 times my entire childhood, and those were simple trips to visit family. I had a happy childhood, but as an adult I want to see the world. And I don't want to be forced to work 40+ hours a week until I'm in my 60's. 

So I don't want to be poor. 

I've saved and clawed my way to a comfortable life. But I fear losing it. So I overwork. Today, I'm well past the "[sweet spot](https://www.mrmoneymustache.com/2020/08/04/the-sweet-spot/)". So I'm dialing back my work schedule as an independent, and enjoying other aspects of life more.

This fear drives my other fears...

1. **Fear of rejection** (from friends, peers) - This drives me to overwork to feel worthy. It's illogical. There are better ways to grow a relationship. I'm so work focused that I'm bad at keeping in touch with old friends. Plus, I worry my call is a bother, so I don't call. To help with this, today I added a recurring reminder to my calendar to contact an old friend.
1. **Fear of dependence**. I've lived my entire life as an extremely independent person. This hurts my relationships. I don't ask friends and family for help or input. And they assume I'm too busy to help, so they don't ask me. For this reason, I also avoid starting anything that requires the help of others.
1. **Fear of not being useful**. "Be useful" has been my mantra for the last decade. But my identity is too wrapped up in what I do to add value in my career. As an independent, I'm dialing back my work hours to be a better dad, son, brother, friend.
1. **Fear of insignificance**. I fear my life not mattering, so I work hard to make an impact. But relationships are also a key aspect of significance, so I'm rebalancing to make time.
1. **Fear of boredom**. I fear boredom, so I say yes to too much work. This leads to overwork. I'm getting better at saying no via Derek Sivers "[Hell yes, or no](https://sive.rs/hellyeah)" mindset. And I'm picking up old hobbies, reading non-tech books, and enjoying more daily family time so boredom outside of work is less of a concern.

Thanks so much for this thoughtful question!

**Comment by accidentaldeveloper** [comment]
Thank you, Cory. This is an incredibly insightful answer. It gives me a lot to chew on as I consider the relevance to my own life and fears.

**Comment by accidentaldeveloper** [comment]
Several years later, how do you rate your progress towards overcoming these fears?

**Comment by coryhouse** [comment]
Wow, I appreciate the follow up on this. Reading this years later is fascinating. I needed the nudge.

I don't worry about significance anymore. I wanted to be famous. I don't care about that anymore.

But I still fear dependence, boredom, and not being useful. So I tend to overcommit, and overwork to build more financial safety and stay relevant. My business often requires more than 40 hours/week, and I haven't set limits. I continue to think "make hay when the sun shines", but that often leads to overwork. 

Work remains my primary hobby, (though I enjoy many other things). So finding work/life balance continues to be a struggle.

> The world is split between those who don’t know how to start making money and those who don’t know when to stop.” — @nntaleb
