### ISSUE TITLE
A question about your course - Securing React Apps with Auth0

### ISSUE THREAD

**Issue by Ismzakata** [coryhouse/ama#28]
Hi Corey,

Firstly, amazing course, I really enjoy your clear, concise and easy to understand approach to teaching courses.

I have a couple of questions about the Plural Sight course Securing React Apps with Auth0. I watched this as I am building an app with a React front end and a Java Spring Boot back end.

1) You mention that if we have a server of any type then we should probably use the authorization grant type. If that's the case why do you use the Implicit flow even when you have an Express server set up in the course?

2) I see the course was released in 2018, is the course above now out of date? I am no security expert myself, but reading around I see that the Implicit grant type is now deprecated and even SPAs like React apps should use the authorization grant flow, what's your opinion on this?

Thanks for taking the time to take a look at my questions and answer them.

**Comment by coryhouse** [comment]
Thanks for the kind feedback!

1. I was torn about that decision. I ultimately decided to avoid using Express for the auth story to avoid people thinking they had to use Express for the course to be relevant.
2. Yes, I plan to update the course soon to show authorization grant flow.

Thanks again for the feedback!

**Comment by Ismzakata** [comment]
Thanks for answering the question and that's awesome, I look forward to watching the updated course.
