### ISSUE TITLE
How do you bounce back from a disappointing day?

### ISSUE THREAD

**Issue by accidentaldeveloper** [coryhouse/ama#32]
I love hearing about your wins: sage advice, new discoveries, and general success stories. But I also wonder, do you have days where you think "That one really got away from me. I could have managed it better."? If so, what strategies do you use to bounce back and make the next day a success?

**Comment by coryhouse** [comment]
Hi Michael - Two things come to mind:

1. When I mess up, I strive to apologize and admit my mistake to the team. I explain the lesson I learned and what I'll do to avoid it happening again. This tends to disarm others. I've already attacked myself. No need to pile it on. It also sends a positive message: I'm candid when I mess up, I learn from my mistakes, and I'm humble enough to admit it. 
2. On those days, I go to bed early. If feel defeated, staying up milling over it doesn't help. I find a full night's sleep is the best medicine for waking up optimistic and recharged. I exercise each morning too, which I find lowers my stress and clears my head.

**Comment by accidentaldeveloper** [comment]
Thank you, Cory!

I think that "2" is particularly valuable. I sometimes find myself stuck in a loop where I feel disappointed with myself, end up seeking out distractions as a result, then feel more disappointed in myself. Sleep helps to break the cycle and give a reset. Exercise is an incredibly effective reset as well.
