### ISSUE TITLE
Integrating .NET Core with Next.js 14 for Backend Services

### ISSUE THREAD

**Issue by briankb** [coryhouse/ama#37]
Hi Cory,

I recently enjoyed your course, "Next.js 12: The Big Picture," and it inspired me to explore Next.js 14. I'm currently wrapping up the new learning path by Vercel for version 14 and delving into the documentation.

I'm curious about the integration possibilities between Next.js 14 and a .NET Core backend. Our team has extensive experience with .NET Core and C#, and we're considering leveraging that expertise for backend services while adopting Next.js for our front end.

Could you shed some light on how the new default to server-side-rendering and 'use client' features in Next.js 14 might impact or facilitate the use of a .NET Core backend? Are there best practices for this kind of setup, especially considering the maturity and security benefits that .NET Core offers?

Thanks for your time

**Comment by coryhouse** [comment]
Hi Brian - To me, Next is a backend, even more so now that it supports React Server Components (RSC). So I would prefer working solely in TypeScript, and potentially even calling the DB directly via RSC. With RSC, there's no need for traditional REST APIs, though they're certainly an option if you prefer.

And sure, there's nothing stopping you from calling a .NET backend, but however you choose to do so isn't really impacted by your choice to use Next. You're making HTTP calls to endpoints regardless of your frontend framework.
