### ISSUE TITLE
Where's the part 2 of the React Most Common Mistakes of 2023 - JetBrains JavaScript Day 2023. 

### ISSUE THREAD

**Issue by hemantatwork** [coryhouse/ama#38]
There are some slides, mistakes and solution on which I want some explanation e.g. https://docs.google.com/presentation/d/1kuBeSh-yTrL031IlmuwrZ8LvavOGzSbo/edit#slide=id.p28
I completely don't understand what this slides says. I will be really good if you provide a complete video explanation to the slides, which means make part 2 of React Most Common Mistakes of 2023 - JetBrains JavaScript Day 2023. As your audience also wants this. Thanks for everything. I hope we meet in real life.

**Comment by coryhouse** [comment]
Sorry, I don't have a part 2 at this time - but when/if I do I will post it here.
