### ISSUE TITLE
Invalidating queries with long query keys.

### ISSUE THREAD

**Issue by TanveerMughal** [coryhouse/ama#39]
Hi, I use React query for my server state management. The issue i am facing the most is invalidating queries. Invalidating a query is simple but if your query key has many parameters then you may not be in scope to get all parameters to invalidate a certain query. There can also be a situation where you increase the number of parameters in the query key later and you forget to put all new entries where those queries are being invalidated. In such a case how can we invalidate a query?

**Comment by coryhouse** [comment]
You can invalidate all the records related to that query:

`invalidateQueries(["users"]) // invalidate all user records`

Or invalidate the entire query cache.

`invalidateQueries();`
