### ISSUE TITLE
React Large and scalable app

### ISSUE THREAD

**Issue by FreakDroid** [coryhouse/ama#4]
Hey Corey, thanks a lot for this AMA. I'm a huge fan of you because I've learned react thanks yours Pluralsight courses, everything is well explained and your support for the course is awesome.

Some months ago,  after I finished the react courses, I started to create a dummy app for my portafolio like a real-app but I saw 3 different things that for me are doubts that could be great ask you:

1. Which architecture do you recommend for large and scalable react's app?  Would be grate if you can give an example.

2. How can you work with react-redux if you have a big amount of data? Becuase I think if you have 1kk of registers is not ok (At least for me) retrieve all the data from your DB or whatever, and put it in your state as you can see in the examples.

3. For you What is the best real-app react-redux app that I can see as an example?

4. When will you create a full unit test for react app course?

Thanks, a lot I hope that you have time to answer those questions.

**Comment by coryhouse** [comment]
1. No simple answer, but Redux and GraphQL would be on my short list. Would also try to split the app.

2. You need not keep everything in the Redux store. Filter on the server to avoid massive datasets that the client can't practically display anyway.

3. Sorry, no great suggestions off-hand

4. It's on my radar :)

**Comment by coryhouse** [comment]
Here's a list of Redux apps: https://github.com/enaqx/awesome-react/blob/master/README.md#example-apps

**Comment by FreakDroid** [comment]
@coryhouse  Thanks a lot, I will check it for sure :smile:
