### ISSUE TITLE
Do you ever feel like you dedicate too much time to your professional life that you don't lead a balanced life?

### ISSUE THREAD

**Issue by mikecole** [coryhouse/ama#5]
You have a pretty active professional life, between your regular work, your community involvement, and your Pluralsight gig, and I'm sure other things I'm not listing. Do you ever stop to wonder why you devote so much time to your professional life? And what you could have accomplished in your personal life with that time dedication?

I personally feel like to be the developer I want to be I can't just do a 40 hour work week. I work extra hours, do other stuff on the side, attend conferences, etc. Are we an industry of workaholics?

**Comment by coryhouse** [comment]
I'm not balanced. And I'm okay with that. 

> "If you want to be an anomaly, you have to act like one." - Gary Vaynerchuck

Each person has to decide what their priorities are and live accordingly. I often question how I'm spending my time and adjust accordingly. Over the years I've cut many hobbies and habits so I can focus more on the things that matter most to me: Family, and making an impact in my little realm of influence.
