### ISSUE TITLE
Server Side Rendering using create-react-app without ejecting app.

### ISSUE THREAD

**Issue by abhisharkjangir** [coryhouse/ama#7]
How we can achieve SSR(server side rendering) using create-react-app(without ejecting), redux, node and react-router-dom? I tried a lot but i'm not able to render component, which are connected to redux on server side. Please help me out on this.

**Comment by coryhouse** [comment]
If you want to render on the server,  I suggest alternatives like [Next.js](https://github.com/zeit/next.js/), [After](https://github.com/jaredpalmer/after.js), [Gatsby](https://www.gatsbyjs.org), or a [long list of universal boilerplates](https://www.javascriptstuff.com/react-starter-projects/#tag:universal).
