### ISSUE TITLE
Pluralsight-redux-starter

### ISSUE THREAD

**Issue by KidNinjja** [coryhouse/ama#9]
Hello, what is the probability that you will update your starting boilerplate for the course? - https://github.com/coryhouse/pluralsight-redux-starter

Thanks in advance, regards, Dmitry!

**Comment by coryhouse** [comment]
Hi Dmitry - Here's a PR that shows how to update the final course demo to the latest versions: https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/pull/1

I plan to update the course videos at some point, but in the meantime, that link will show you how to tweak the boilerplate. :) Thanks for the question!
